version: 2
jobs:
  setup:
    docker:
      - image: gplane/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
  test:
    docker:
      - image: gplane/pnpm:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test and Lint
          command: pnpm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
